# Generated by Django 3.1.6 on 2023-06-27 16:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=256)),
                ('blog_subtitle', models.CharField(max_length=4800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_description', tinymce.models.HTMLField()),
                ('blog_tag', models.CharField(max_length=128)),
                ('blog_background', models.CharField(max_length=480)),
            ],
        ),
    ]
