# Generated by Django 3.1.6 on 2023-07-01 07:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_category', models.CharField(max_length=256)),
                ('prayer_category_tag', models.CharField(max_length=256)),
                ('prayer_category_tagline', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_name', models.CharField(max_length=1248)),
                ('prayer_category', models.CharField(max_length=256)),
                ('prayer_to', models.CharField(max_length=256)),
                ('prayer_type', models.CharField(max_length=128)),
                ('prayer_description', models.CharField(max_length=4800)),
                ('prayer_attributed_to', models.CharField(max_length=256)),
                ('prayer_content', tinymce.models.HTMLField()),
                ('prayer_category_tag', models.CharField(max_length=256)),
                ('prayer_name_tag', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_name', models.CharField(max_length=1248)),
                ('prayer_description', models.CharField(max_length=4800)),
                ('prayer_content', tinymce.models.HTMLField()),
                ('prayer_article', tinymce.models.HTMLField()),
                ('prayer_category_tag', models.CharField(max_length=256)),
                ('prayer_name_tag', models.CharField(max_length=256)),
                ('prayer_image', models.CharField(max_length=256)),
            ],
        ),
    ]
